create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  artikel text not null,
  barcode text,
  bild_url text,
  kategorie text not null,
  mhd date not null,
  menge integer default 1 not null,
  mitarbeiter text not null,
  user_id uuid references auth.users(id)
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  artikel text not null,
  barcode text,
  bild_url text,
  kategorie text not null,
  mhd date,
  menge integer default 1 not null,
  grund text not null,
  mitarbeiter text not null,
  user_id uuid references auth.users(id)
);

alter table public.mhd_artikel enable row level security;
alter table public.abschriften enable row level security;

drop policy if exists "mhd lesen" on public.mhd_artikel;
drop policy if exists "mhd anlegen" on public.mhd_artikel;
drop policy if exists "mhd loeschen" on public.mhd_artikel;
drop policy if exists "abschriften lesen" on public.abschriften;
drop policy if exists "abschriften anlegen" on public.abschriften;

create policy "mhd lesen" on public.mhd_artikel for select to authenticated using (true);
create policy "mhd anlegen" on public.mhd_artikel for insert to authenticated with check (auth.uid() = user_id);
create policy "mhd loeschen" on public.mhd_artikel for delete to authenticated using (true);
create policy "abschriften lesen" on public.abschriften for select to authenticated using (true);
create policy "abschriften anlegen" on public.abschriften for insert to authenticated with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('artikelbilder','artikelbilder',true) on conflict (id) do nothing;

drop policy if exists "artikelbilder lesen" on storage.objects;
drop policy if exists "artikelbilder hochladen" on storage.objects;
create policy "artikelbilder lesen" on storage.objects for select using (bucket_id='artikelbilder');
create policy "artikelbilder hochladen" on storage.objects for insert to authenticated with check (bucket_id='artikelbilder');
