-- 1) Tabellen
create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  artikel text not null,
  barcode text,
  kategorie text not null,
  mhd date not null,
  menge integer default 1 not null,
  mitarbeiter text not null,
  bild_url text,
  user_id uuid references auth.users(id)
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  artikel text not null,
  barcode text,
  kategorie text not null,
  mhd date,
  menge integer default 1 not null,
  grund text not null,
  mitarbeiter text not null,
  bild_url text,
  user_id uuid references auth.users(id)
);

-- 2) Sicherheit aktivieren
alter table public.mhd_artikel enable row level security;
alter table public.abschriften enable row level security;

-- 3) Policies: nur eingeloggte Mitarbeiter
create policy "mhd lesen" on public.mhd_artikel for select to authenticated using (true);
create policy "mhd anlegen" on public.mhd_artikel for insert to authenticated with check (auth.uid() = user_id);
create policy "mhd loeschen" on public.mhd_artikel for delete to authenticated using (true);
create policy "abschriften lesen" on public.abschriften for select to authenticated using (true);
create policy "abschriften anlegen" on public.abschriften for insert to authenticated with check (auth.uid() = user_id);

-- 4) Storage-Bucket fuer eigene Artikelbilder
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "bilder lesen" on storage.objects for select using (bucket_id = 'product-images');
create policy "bilder hochladen" on storage.objects for insert to authenticated with check (bucket_id = 'product-images');
