-- Finale MHD-App Datenbankstruktur
-- In Supabase SQL Editor ausführen.

create table if not exists public.mitarbeiter (
  id bigint generated by default as identity primary key,
  nummer text unique not null,
  passwort text not null,
  name text not null,
  aktiv boolean default true,
  created_at timestamp with time zone default now()
);

create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  artikel text not null,
  barcode text,
  kategorie text default 'Sonstiges',
  mhd date not null,
  menge integer default 1,
  bild_url text,
  mitarbeiter text,
  created_by text
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  artikel text not null,
  barcode text,
  kategorie text,
  mhd date,
  menge integer default 1,
  grund text not null,
  mitarbeiter text,
  bild_url text
);

-- Einfach für internen Tankstellenbetrieb: RLS aus, weil App eigenen Mitarbeiterlogin nutzt.
alter table public.mitarbeiter disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;

-- Beispiel-Mitarbeiter, später ändern/löschen.
insert into public.mitarbeiter (nummer, passwort, name)
values ('9','1994','Christian'), ('19','5678','Michael')
on conflict (nummer) do nothing;

-- Storage Bucket für eigene Produktbilder. Falls Fehler kommt: in Supabase Storage manuell Bucket artikelbilder public erstellen.
insert into storage.buckets (id, name, public)
values ('artikelbilder', 'artikelbilder', true)
on conflict (id) do nothing;
