import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { Barcode, Bell, Camera, ClipboardList, LogOut, Plus, RefreshCw, Search, Trash2, Upload } from 'lucide-react';
import './style.css';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
const categories = ['Kühlung','Getränke','Milchprodukte','Snacks','Süßwaren','Backshop','Sonstiges'];
const staff = ['Michael','Ali','Mara','Sven','Lisa','Nina','Tom'];

function employeeEmail(number){ return `${String(number).trim()}@tankstelle.local`; }
function daysUntil(date){ const t=new Date(); t.setHours(0,0,0,0); return Math.ceil((new Date(date+'T00:00:00')-t)/86400000); }
function status(item){ const d=daysUntil(item.mhd); if(d<0) return ['Abgelaufen','bad']; if(d<=2) return ['Bald','warn']; if(d<=7) return ['Diese Woche','soon']; return ['OK','ok']; }
function mapCategory(p){ const txt=`${p.categories||''} ${p.categories_tags?.join(' ')||''}`.toLowerCase(); if(/drink|beverage|getränk|cola|wasser|saft|energy/.test(txt)) return 'Getränke'; if(/milk|dairy|joghurt|käse/.test(txt)) return 'Milchprodukte'; if(/snack|chips|nuts|nüsse/.test(txt)) return 'Snacks'; if(/chocolate|candy|sweet|süß/.test(txt)) return 'Süßwaren'; if(/bakery|bread|sandwich|croissant/.test(txt)) return 'Backshop'; return 'Sonstiges'; }
async function fetchProduct(barcode){ if(!barcode) return null; try{ const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${barcode}.json?fields=product_name,brands,image_front_url,categories,categories_tags`); const d=await r.json(); if(d.status!==1) return null; const p=d.product; return { artikel:[p.brands,p.product_name].filter(Boolean).join(' · ')||barcode, kategorie:mapCategory(p), bild_url:p.image_front_url||'' }; }catch{return null;} }
async function registerSW(){ if('serviceWorker' in navigator) try{ await navigator.serviceWorker.register('/sw.js'); }catch(e){ console.warn(e); } }
async function notify(items){ if(!('Notification' in window)) return; if(Notification.permission!=='granted'){ const p=await Notification.requestPermission(); if(p!=='granted') return; } const exp=items.filter(i=>daysUntil(i.mhd)<=2); const body=exp.length?exp.slice(0,5).map(i=>`${i.artikel} · MHD ${new Date(i.mhd).toLocaleDateString('de-DE')}`).join('\n'):'Aktuell läuft nichts innerhalb von 2 Tagen ab.'; const reg=await navigator.serviceWorker?.ready; (reg?.showNotification?reg.showNotification('MHD Warnung',{body,tag:'mhd'}):new Notification('MHD Warnung',{body})); }
async function scanBarcode(){ if(!('BarcodeDetector' in window)){ alert('Barcode-Scan wird auf diesem Gerät nicht unterstützt. Bitte Barcode manuell eingeben.'); return null; } const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}}); const video=document.createElement('video'); video.srcObject=stream; video.playsInline=true; await video.play(); const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128']}); return new Promise(resolve=>{ let done=false; const overlay=document.createElement('div'); overlay.className='scannerOverlay'; overlay.innerHTML='<div>Barcode vor die Kamera halten</div>'; const cancel=document.createElement('button'); cancel.textContent='Abbrechen'; cancel.onclick=()=>stop(null); overlay.append(video,cancel); document.body.appendChild(overlay); function stop(v){ if(done) return; done=true; stream.getTracks().forEach(t=>t.stop()); overlay.remove(); resolve(v); } async function loop(){ if(done) return; const codes=await detector.detect(video).catch(()=>[]); if(codes.length) return stop(codes[0].rawValue); requestAnimationFrame(loop); } loop(); }); }

function App(){
  const [session,setSession]=useState(null),[authLoading,setAuthLoading]=useState(true);
  const [num,setNum]=useState(''),[pw,setPw]=useState(''),[loginErr,setLoginErr]=useState('');
  const [items,setItems]=useState([]),[writeOffs,setWriteOffs]=useState([]),[view,setView]=useState('artikel'),[q,setQ]=useState(''),[cat,setCat]=useState('alle'),[err,setErr]=useState(''),[loading,setLoading]=useState(false);
  const [form,setForm]=useState({artikel:'',barcode:'',kategorie:'Kühlung',mhd:'',menge:'',mitarbeiter:'Michael',bild_url:''});
  useEffect(()=>{ registerSW(); supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe(); },[]);
  async function login(){ setLoginErr(''); const {error}=await supabase.auth.signInWithPassword({email:employeeEmail(num),password:pw}); if(error) setLoginErr('Login fehlgeschlagen. Nummer oder Passwort prüfen.'); }
  async function load(){ if(!session)return; setLoading(true); const a=await supabase.from('mhd_artikel').select('*').order('mhd',{ascending:true}); const b=await supabase.from('abschriften').select('*').order('created_at',{ascending:false}); if(a.error) setErr('Artikel konnten nicht geladen werden.'); else setItems(a.data||[]); if(!b.error) setWriteOffs(b.data||[]); setLoading(false); }
  useEffect(()=>{ if(!session)return; load(); const ch=supabase.channel('live').on('postgres_changes',{event:'*',schema:'public',table:'mhd_artikel'},load).on('postgres_changes',{event:'*',schema:'public',table:'abschriften'},load).subscribe(); return()=>supabase.removeChannel(ch); },[session]);
  const filtered=useMemo(()=>items.filter(i=>(cat==='alle'||i.kategorie===cat)&&`${i.artikel} ${i.barcode||''} ${i.mitarbeiter}`.toLowerCase().includes(q.toLowerCase())),[items,q,cat]);
  const stats={total:items.length,bad:items.filter(i=>daysUntil(i.mhd)<0).length,warn:items.filter(i=>daysUntil(i.mhd)>=0&&daysUntil(i.mhd)<=2).length,week:items.filter(i=>daysUntil(i.mhd)>2&&daysUntil(i.mhd)<=7).length};
  async function uploadImage(file){ if(!file) return ''; const ext=file.name.split('.').pop()||'jpg'; const path=`products/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`; const {error}=await supabase.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false}); if(error){setErr('Bild konnte nicht hochgeladen werden.'); return '';} const {data}=supabase.storage.from('product-images').getPublicUrl(path); return data.publicUrl; }
  async function lookup(code=form.barcode){ const p=await fetchProduct(code); if(p) setForm(f=>({...f, artikel:f.artikel||p.artikel, kategorie:p.kategorie||f.kategorie, bild_url:p.bild_url||f.bild_url})); else setErr('Kein automatischer Produktname gefunden. Bitte manuell eintragen.'); }
  async function doScan(){ const code=await scanBarcode(); if(code){ setForm(f=>({...f,barcode:code})); await lookup(code); } }
  async function add(){ setErr(''); if(!form.artikel||!form.mhd){setErr('Bitte Artikel und MHD eintragen.'); return;} const {error}=await supabase.from('mhd_artikel').insert({...form,menge:Number(form.menge||1),user_id:session.user.id}); if(error) setErr('Artikel konnte nicht gespeichert werden.'); else {setForm({artikel:'',barcode:'',kategorie:'Kühlung',mhd:'',menge:'',mitarbeiter:form.mitarbeiter,bild_url:''}); load();} }
  async function remove(id){ await supabase.from('mhd_artikel').delete().eq('id',id); load(); }
  async function writeOff(item, grund='Abgelaufen'){ await supabase.from('abschriften').insert({artikel:item.artikel,barcode:item.barcode,kategorie:item.kategorie,mhd:item.mhd,menge:item.menge,grund,mitarbeiter:form.mitarbeiter,bild_url:item.bild_url,user_id:session.user.id}); await remove(item.id); }
  if(authLoading) return <main className='center'>Lade App...</main>;
  if(!session) return <main className='login'><section className='card loginCard'><h1>MHD App</h1><p>Bestands- & MHD-Verwaltung</p><label>Mitarbeiter Nummer</label><input placeholder='z.B. 01' value={num} onChange={e=>setNum(e.target.value)}/><label>Passwort (4-stellig)</label><input type='password' inputMode='numeric' value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()}/><button onClick={login}>Anmelden</button>{loginErr&&<b className='error'>{loginErr}</b>}<small>Shell Station Völklingen Ludweiler</small></section></main>;
  return <main className='app'><header><div><h1>MHD Dashboard</h1><p>Shell Station Völklingen Ludweiler</p></div><div className='actions'><button onClick={()=>notify(items)}><Bell/> Warnung testen</button><button onClick={load}><RefreshCw/> Aktualisieren</button><button onClick={()=>supabase.auth.signOut()}><LogOut/> Abmelden</button></div></header><section className='stats'><Stat t='Gesamt' v={stats.total}/><Stat t='Abgelaufen' v={stats.bad} c='bad'/><Stat t='Bald' v={stats.warn} c='warn'/><Stat t='Diese Woche' v={stats.week} c='soon'/></section><nav><button onClick={()=>setView('artikel')} className={view==='artikel'?'active':''}>Artikel</button><button onClick={()=>setView('abschriften')} className={view==='abschriften'?'active':''}><ClipboardList/> Abschriften</button><button onClick={()=>setView('backwaren')} className={view==='backwaren'?'active':''}>Backwaren Tagesende</button></nav>{err&&<p className='errorBox'>{err}</p>}<section className='card form'><input placeholder='Artikelname' value={form.artikel} onChange={e=>setForm({...form,artikel:e.target.value})}/><div className='row'><input placeholder='Barcode' value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})} onBlur={()=>lookup()}/><button onClick={doScan}><Barcode/> Scan</button></div><select value={form.kategorie} onChange={e=>setForm({...form,kategorie:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select><input type='date' value={form.mhd} onChange={e=>setForm({...form,mhd:e.target.value})}/><input type='number' min='1' placeholder='Menge' value={form.menge} onChange={e=>setForm({...form,menge:e.target.value})}/><select value={form.mitarbeiter} onChange={e=>setForm({...form,mitarbeiter:e.target.value})}>{staff.map(x=><option key={x}>{x}</option>)}</select><label className='upload'><Upload/> Eigenes Artikelbild<input type='file' accept='image/*' capture='environment' onChange={async e=>{const url=await uploadImage(e.target.files?.[0]); if(url)setForm(f=>({...f,bild_url:url}));}}/></label>{form.bild_url&&<img className='preview' src={form.bild_url}/>}<button className='primary' onClick={add}><Plus/> Artikel speichern</button></section>{view==='artikel'&&<><section className='filters'><div><Search/><input placeholder='Suchen nach Artikel, Barcode oder Mitarbeiter' value={q} onChange={e=>setQ(e.target.value)}/></div><select value={cat} onChange={e=>setCat(e.target.value)}><option value='alle'>Alle Kategorien</option>{categories.map(x=><option key={x}>{x}</option>)}</select></section><section className='list'>{loading?'Lade...':filtered.map(i=><Item key={i.id} item={i} remove={remove} writeOff={writeOff}/>)}</section></>}{view==='abschriften'&&<WriteOffs data={writeOffs}/>} {view==='backwaren'&&<Bakery items={items} writeOff={writeOff}/>}</main>;
}
function Stat({t,v,c=''}){return <div className={`stat ${c}`}><b>{v}</b><span>{t}</span></div>}
function Item({item,remove,writeOff}){ const [s,c]=status(item); return <article className={`card item ${c}`}>{item.bild_url&&<img src={item.bild_url}/>}<div><h3>{item.artikel}</h3><p>{item.kategorie} {item.barcode&&`· ${item.barcode}`}</p></div><b>MHD {new Date(item.mhd).toLocaleDateString('de-DE')}</b><span>{item.menge} Stk.</span><em>{s}</em><button onClick={()=>writeOff(item,daysUntil(item.mhd)<0?'Abgelaufen':'Sonstiges')}>Abschrift</button><button className='ghost' onClick={()=>remove(item.id)}><Trash2/></button></article> }
function WriteOffs({data}){ const today=new Date().toISOString().slice(0,10); const rows=data.filter(x=>x.created_at?.slice(0,10)===today); return <section className='list'><h2>Abschriften heute</h2>{rows.map(x=><article className='card item' key={x.id}>{x.bild_url&&<img src={x.bild_url}/>}<div><h3>{x.artikel}</h3><p>{x.grund}</p></div><b>{x.menge} Stk.</b><span>{x.mitarbeiter}</span></article>)}{!rows.length&&<p className='empty'>Heute noch keine Abschriften.</p>}</section> }
function Bakery({items,writeOff}){ const rows=items.filter(i=>i.kategorie==='Backshop'||i.kategorie==='Backwaren'); return <section className='list'><h2>Backwaren Tagesende</h2>{rows.map(i=><article className='card item' key={i.id}>{i.bild_url&&<img src={i.bild_url}/>}<div><h3>{i.artikel}</h3><p>{i.menge} Stk. verfügbar</p></div><button onClick={()=>writeOff(i,'Backwaren Tagesende')}>Als Tagesabschrift</button></article>)}{!rows.length&&<p className='empty'>Keine Backwaren vorhanden.</p>}</section> }
createRoot(document.getElementById('root')).render(<App/>);
